sudo: false

language: node_js

node_js:
  - "v10.13.0"

env:
 global:
    - export COVERALLS_REPO_TOKEN=RWqmqUaQfZ888bV68WpvhREH0L27uOgaS
    - export NODE_ENV=test
    - export TEST_DB_DATABASE=hzcwkfdn
    - export TEST_DB_USER=hzcwkfdn
    - export TEST_DB_PASSWORD=i7krwq1d9GeqQ8RrrAD7m1tNCd5kyprG
    - export TEST_DB_HOST=ruby.db.elephantsql.com
    - export EMAIL_USERNAME=88b41fce5c457e
    - export EMAIL_PASSWORD=1e0308731e6e44
    - export EMAIL_HOST=smtp.mailtrap.io
    - export EMAIL_PORT=25

cache: npm

before_install:
  - npm config set spin false
  - npm install -g standard

script:
  - npm run test:cover

after_success:
- npm run coveralls